### ISSUE TITLE
docker-compose up fails if postgres running on host

### ISSUE THREAD

**Issue by gabestein** [worb/launchpad#2]
If you have postgres running on the host on the default port (5342), `docker-compose up` can fail with the following error:

```ERROR: for postgres  Cannot start service postgres: driver failed programming external connectivity on endpoint launchpad_postgres_1 (73336953f70d0ee21b872441a12aba5a5d40182f1cce3cfd7b287c3b32d377af): Error starting userland proxy: Bind for 0.0.0.0:5432 failed: port is already allocated```

**Comment by allanlasser** [comment]
I don't consider this a bug. Docker maps ports from its virtual machine to ports on the host machine, in this case mapping its Postgres instance to the default Postgres port on your machine. If that port is occupied, then it should fail.

We could map Postgres to a non-default port on the host machine. I don't know what the expectation that somebody will be running Postgres on their own machine, but two simultaneous instances of Launchpad would conflict in that case also. An extreme solution would be to not expose the Postgres ports to hosts at all.

**Comment by allanlasser** [comment]
I'm going to close this issue. Exposing the port to the host machine using the Postgres default is very helpful for a starter kit. If multiple simultaneous Postgres instances need to be run at the same time, then the user can customize the Postgres ports to whatever they want in order to avoid the collision.

**Comment by gabestein** [comment]
Hrm. I thought you weren't supposed to need to do a local npm/yarn install,
that everything needed was installed in docker. So that's probably the step
I was missing.
