### ISSUE TITLE
npm test fails due to missing eslint

### ISSUE THREAD

**Issue by gabestein** [worb/launchpad#3]
Running `npm test` after a clean install fails with the following error:

```
> launchpad@0.0.0 test /Users/gabe/code/worb/launchpad
> npm run lint && npm run mocha


> launchpad@0.0.0 lint /Users/gabe/code/worb/launchpad
> eslint src/

sh: eslint: command not found
```

**Comment by allanlasser** [comment]
This is odd, since `eslint` is included as a dependency in `package.json`. I'll try to build from scratch and see if I can reproduce.

**Comment by allanlasser** [comment]
I couldn't reproduce this issue with either `yarn` or `npm install`. I do not have `eslint` installed globally. Here were the steps I took:

1. `git clone git@github.com:worb/launchpad.git`
2. `yarn` / `npm install`
3. `npm test`
